### ISSUE TITLE
Dead Repository

### ISSUE THREAD

**Issue by chaughawout** [nickperkinslondon/angular-bootstrap-nav-tree#114]
It is obvious that the owner of this repository has no intent to maintain this repository any longer. He has 4 contributions on github in the last year as of this moment. There are 59 open issues prior to this one and 13 pending pull-requests ranging from December 15 2014 to today.

Is anyone willing to take on maintaining this code base? @nickperkinslondon are you willing to pass ownership of the repository to the next maintainer?

**Comment by Nilzone-** [comment]
Hopefully someone will keep maintaining this. 

I would really love the possibility to add a right-click handler.

**Comment by chaughawout** [comment]
@nickperkinslondon I see you merged a pull request a few days ago. Does that mean that you're continuing support for this component? Any communication is appreciated.

**Comment by funkytaco** [comment]
He merged #77 which I submitted a long ways back. Maybe he just needs more maintainers.

**Comment by nickperkinslondon** [comment]
Hi everyone.  I created this thing a few years ago while on vacation, just for fun and learning.  I am pleasantly surprised by the number of people who have used it.  However, I did not anticipate that I would get so many feature requests, even years later.  I never had any intention of maintaining this thing into the future.  In fact, I don't even use Angular any more ( I have used React for a while, and now I am trying to learn Elm ).  

So, yes, I am willing to pass the torch to someone else.  How is that done?  If there is a fork that will be maintained I would be happy to deprecate this package and put a prominent "re-direct" to it.  So...who would like to take over this project?

**Comment by tuanjinn** [comment]
Has anyone taken over this from @nickperkinslondon yet?

**Comment by stevenvachon** [comment]
I'm thinking of using https://github.com/wix/angular-tree-control instead

**Comment by daerogami** [comment]
Hey all, I have started addressing and cleaning up old issues/PRs. I would like to, at the very least, fix or close all issues/PRs. I may also investigate updating this project to current gen tooling (typescript instead of coffeescript, gulp instead of grunt, investigate implementing component version for modern angular, etc...)
Hopefully I can breathe a little more life into this really useful library and help us get that much more out of it. It seems that there is no shortage of similar libraries, but this is one that a long standing project at my work uses so I have a vested interest in keeping it alive for the near future.
Any assistance or feedback is appreciated as I clean the cobwebs and start moving PRs. Thanks!
