### ISSUE TITLE
Problems when you have two trees in the same HTML page.

### ISSUE THREAD

**Issue by ajoys** [nickperkinslondon/angular-bootstrap-nav-tree#55]
If you have two tree's on the same page using the same tree-data, It sometimes makes it look like you are selecting two things when you click a branch of one tree, and a branch of the other. Also, when you are trying to set the initial date using an angular model on both, one of the two needs to be in the curly braces.

**Comment by daerogami** [comment]
I have a page where I use two trees and don't have this issue but you mentioned you are using the same tree-data? You may need to run it through `angular.copy()` before passing it to the tree because it may be calling the same references, thus 'binding' the two together.

Feel free to reopen if this is still an issue.
