### ISSUE TITLE
Saving the tree expanded state.

### ISSUE THREAD

**Issue by vikasgupta1986** [nickperkinslondon/angular-bootstrap-nav-tree#81]
Is it possible to save the state of the expanded tree. Lets say i have a page that displays the tree, then i navigate to a different page. I come back to the tree page again, i'd like to keep the tree expanded state.

**Comment by er-paramjitsaini** [comment]
I also need this type of feature, but on the same page. I am pushing the new tree record data through ajax. Data is properly added into tree but tree is collapse after tree data change. Any help please?

**Comment by daerogami** [comment]
It might be possible to persist the tree data to session storage, initialize the tree then push the persisted data instead of using the ajax call. Any solution will involve application infrastructure for persistence and re-population.

You will need to save the tree data itself then either re-hydrate the new tree instance with it or programmatically re-expand the branches.

If this is still an issue, re-open and we can discuss alternative solutions.
